### ISSUE TITLE
Update packaging

### ISSUE THREAD

**Issue by IAlibay** [openforcefield/openff-nagl#85]
## Is your feature request related to a problem? ##

Follow up from previous issues - a few nice to haves to packaging especially as we start looking at supporting NAGL downstream.

## Describe the solution you'd like ##

Couple of quick thoughts, there's probably more:

- Upgrading versioneer to be py3.12 compatible (or making it clear that it isn't compatible, or switching to an alternate versioning alternative)
- Switching to a pyproject.toml (just a nice to have)
- Bumping up the minimum supported Python version? (cf indicates 3.9+ and setup.py indicates 3.8 if I remember correctly)
- Support for pydantic 2.0? (downstream is planning to switch soon)

**Comment by mattwthompson** [comment]
* I started #86 which may or may not get things spinning on 3.12, who knows
* I don't use `pyproject.toml` myself and seem to have generally missed the boat on where it must be used.
* The last release is 3.9+, at least on the conda side of things. I can't release OpenFF tools on PyPI right now so there might be something different going on in that space.
* Pydantic v1/v2 (runtime) compatibility should already be out in the world (#46 / version 0.3.3)

**Comment by mattwthompson** [comment]
There appears to be no DGL on 3.12?

* https://anaconda.org/conda-forge/dgl/files
* https://anaconda.org/dglteam/dgl/files

**Comment by IAlibay** [comment]
Thanks @mattwthompson !

I should clarify, I was mostly just reading `setup.py` here - I have absolutely no idea what is possible or not.

Re: `pyproject.toml` - I woud have been happy to help out if necessary but I'm out of office for a bit starting today so I probably won't have time to catch up, maybe @dwhswenson can lend a hand if necessary with POSE powers?

**Comment by dwhswenson** [comment]
Yeah, in principle, bringing things up to current recommended practice is within POSE scope. Although TBH, I'm going to have to learn how to do the `pyproject.toml` transition as well, since I've always been a `setup.cfg` person, myself.

I assume this isn't an urgent task? A broader plan to transition OpenFF projects to `pyproject.toml` would be a good topic for the first OpenFF/POSE devs meeting, which should get scheduled for late Feb/early March.

**Comment by mattwthompson** [comment]
> I assume this isn't an urgent task?

This repo is Lily's domain but in general, for our infrastructure I don't see any urgency.

When we get to it, I'd like to learn more about the tradeoffs - until I can ship our ecosystem on PyPI I'm unaware of the benefits

**Comment by lilyminium** [comment]
FWIW this repo started off with a mostly-functional pyproject.toml, so it should be in the history somewhere and can be revived! I removed it due to https://github.com/openforcefield/openff-nagl/issues/28 and haven't revisited it yet, but can do if/when it becomes a priority.

**Comment by lilyminium** [comment]
> There appears to be no DGL on 3.12?

There's no OpenEye for 3.12 currently either, but I've added tests for non-DGL, RDKit-only installations in #87.

**Comment by lilyminium** [comment]
@IAlibay we would like to release NAGL as a fully supported method soon so I'm going through and prioritising technical issues. Are the issues raised here still problematic for you? I'll jot down the changes since the issue was first opened:

* versioneer: I haven't directly checked how up-to-date this is yet, but we have tests running on Python 3.12
* pyproject.toml: I'll keep this low-priority for now while the toolkit and Interchange still don't use it for packaging
* minimum supported Python versions: 3.10+ in both setup.py and conda now
* support for Pydantic 2.0: in place and tested, thanks to Matt

**Comment by IAlibay** [comment]
Thanks for the ping @lilyminium 

As mentioned in the original isssue text, these are "nice to haves" - the list you give seems reasonable, as long as the packaging is consistent and clear then there are no issues downstream.

**Comment by lilyminium** [comment]
Great, thanks! In that case I'll close this issue for now as we have #28 for pyproject.toml currently.
